language: python
cache:
  pip: true
  directories:
  - $TRAVIS_BUILD_DIR/.tox

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-dj111
    python: 2.7
  - env: TOX_ENV=py34-dj111
    python: 3.4
  - env: TOX_ENV=py35-dj111
    python: 3.5
  - env: TOX_ENV=py36-dj111
    python: 3.6
  - env: TOX_ENV=py34-dj20
    python: 3.4
  - env: TOX_ENV=py35-dj20
    python: 3.5
  - env: TOX_ENV=py36-dj20
    python: 3.6
  - env: TOX_ENV=py37-dj20
    python: 3.7
  - env: TOX_ENV=py35-dj21
    python: 3.5
  - env: TOX_ENV=py36-dj21
    python: 3.6
  - env: TOX_ENV=py37-dj21
    python: 3.7
  - env: TOX_ENV=py36-dj22
    python: 3.6
  - env: TOX_ENV=py37-dj22
    python: 3.7
  - env: TOX_ENV=py38-dj22
    python: 3.8
  - env: TOX_ENV=py39-dj22
    python: 3.9
  - env: TOX_ENV=py36-dj31
    python: 3.6
  - env: TOX_ENV=py37-dj31
    python: 3.7
  - env: TOX_ENV=py38-dj31
    python: 3.8
  - env: TOX_ENV=py39-dj31
    python: 3.9
  - env: TOX_ENV=py36-dj32
    python: 3.6
  - env: TOX_ENV=py37-dj32
    python: 3.7
  - env: TOX_ENV=py38-dj32
    python: 3.8
  - env: TOX_ENV=py39-dj32
    python: 3.9
  - env: TOX_ENV=py38-djmain
    python: 3.8
  - env: TOX_ENV=py39-djmain
    python: 3.9
  - env: TOX_ENV=flake8
    python: 3.6
  allow_failures:
  - env: TOX_ENV=py38-djmain
  - env: TOX_ENV=py39-djmain

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q -U tox

# Command to run tests, e.g. python setup.py test
script:
- tox -e "${TOX_ENV}"
